#!/usr/bin/sh
set -e

nasm -f elf32 ./src/entrypoint.asm -o entrypoint.o
nasm -f elf32 ./src/bootseq/boot.asm -o boot.o
nasm -f elf32 ./src/constants.asm -o constants.o
nasm -f elf32 ./src/bootseq/stack.asm -o stack.o
nasm -f elf32 ./src/printk.asm -o printk.o

g++ -m32 -march=i386 -mtune=generic \
    -O2 \
    -ffreestanding -fno-stack-protector \
    -fno-exceptions -fno-rtti -fno-asynchronous-unwind-tables \
    -fno-unwind-tables -fno-pic -fno-PIE \
    -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -Wno-write-strings \
    -c src/*.cpp

gcc -m32 -march=i386 \
    -ffreestanding -fno-stack-protector \
    -fno-asynchronous-unwind-tables -Wwrite-strings \
    -c src/*.c

ld -m elf_i386 -T src/linker.ld \
    $(find . -name "*.o") \
    -o iso/boot/kernel.elf --entry=_start

grub-mkrescue -o kernel.iso iso/
